### ISSUE TITLE
Nothing is being recorded

### ISSUE THREAD

**Issue by suzeeparker** [tomgallagher/RecordReplay#2]
When I start a test, the Start URL page doesn't open even though the "Recording icon" is spinning.  It looks like a nice extension, but how come nobody has rated it?  Is it safe.  I've been getting out of memory errors since I tried using it.

**Comment by tomgallagher** [comment]
Hi there!

Thanks for getting in touch. The extension has only been released for a couple of months and it has only acquired around 20 users so far. No-one has decided to rate it as yet, either well or badly.

I can assure you it's safe, that's why I wanted to publish all the code for it on Github, so people could look through it themselves and check in the browser that the code is the same.

As to your particular issue, maybe you could help me by supplying a URL? Or having a look in the console to see if there are any errors? 

I will then endeavour to help you if I can.

Tom
